Algoritmo "Aula13.04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2023
Var
//b1, b2, altura, area:real
//peso,altura,imc:inteiro

a:real
b:inteiro

Inicio

//b1<-20
//b2<-50
//altura<-70
//area<-(b1+b2)/2* altura;
//peso<-2
//altura<-5
//imc<-peso % altura

a<-5.0
b<- int (a)

escreval(b)


Fimalgoritmo