Algoritmo "estruturas repeat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2023
Var
// Seção de Declarações das variáveis 
x,y,i:inteiro



Inicio
x <- 4
y <- 0

para i de x ate 1 passo -1 faca
     y <- y+i
fimpara

 Escreval(y)
Fimalgoritmo