Algoritmo "Primeiro Algorítimo"

Var
//
nome:caractere
peso:inteiro
altura:real
idade:inteiro
inc:inteiro

//  atribuição das variáveis e do seu valor '<-'
Inicio
nome<-"Maria"
idade<-10
altura<-1.65
peso<-55
inc<-23

//utilizar 'espaços' entre "."
escreva(" A ", nome, " pesa ", peso, " kg ", " mede ", altura, " cm e tem um inc = ", inc )
//comoando escreva (seguido) ou escreval(corta para outra linha)

//escreva("Olá Mundo!")
//escreval("My name is Aromantic.")
Fimalgoritmo