CREATE DATABASE BD_REGISTO;

USE BD_REGISTO;

CREATE TABLE TAB_PESSOAS(
	NOME VARCHAR(30),
    MORADA VARCHAR(30),
    LOCALIDADE VARCHAR(30),
    LIMITE FLOAT);
    
INSERT INTO TAB_PESSOAS VALUES 
	
	('JOÃO', 'RUA DAS ALMAS', 'CÉU', 123.5),
	('MARIA','AVENIDA DO PREGATÓRIO','ALÉM',654.2),
    ('JOSÉ','PRACETA DA MÁ LÍNGUA','COVIL',987.9),
    ('FERNANDA','LARGO DO ANDAIME','OBRA',963.4),
    ('ULTIMO', 'TRAVESSA DO MEIO', 'FINAL',842.7);
    
SELECT * FROM TAB_PESSOAS;